//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINTDELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POINTDELIVERY()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public string IDPOINTDELIVERY { get; set; }
        public Nullable<int> IDTOWN { get; set; }
        public Nullable<int> IDOUTSIDE { get; set; }
        public Nullable<int> NUMOUTSIDE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        public virtual OUTSIDE OUTSIDE { get; set; }
        public virtual TOWN TOWN { get; set; }
    }
}
