//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOVARS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOVARS()
        {
            this.ORDERHASTOVAR = new HashSet<ORDERHASTOVAR>();
        }
    
        public string IDTOVARS { get; set; }
        public Nullable<int> IDNAMETOVAR { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> DISCOUNTMAX { get; set; }
        public Nullable<int> IDMANUFACTURE { get; set; }
        public Nullable<int> IDCATEGORY { get; set; }
        public Nullable<int> DISCOUNTNOW { get; set; }
        public Nullable<int> AMOUNTSTORE { get; set; }
        public string DESCRIPTIONS { get; set; }
        public string IMAGENAME { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual MANUFACTURE MANUFACTURE { get; set; }
        public virtual NAMETOVAR NAMETOVAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERHASTOVAR> ORDERHASTOVAR { get; set; }
    }
}
